language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
# FIXME uncomment it once possibe
# see https://github.com/travis-ci/travis-ci/issues/9717
#  - 7.3
matrix:
  include:
    # `php: ..` in here is just descriptive/for UI, they don't affect installed ver.
    - os: osx
      php: "5.6"
      language: generic
      before_install:
        - brew update && brew install php@5.6 && brew link --force --overwrite php@5.6
    - os: osx
      php: "7.0"
      language: generic
      before_install:
        - brew update && brew install php@7.0 && brew link --force --overwrite php@7.0
    - os: osx
      php: "7.1"
      language: generic
      before_install:
        - brew update && brew install php@7.1 && brew link --force --overwrite php@7.1
    - os: osx
      php: "7.2"
      language: generic
      before_install:
        - brew update && brew install php@7.2 && brew link --force --overwrite php@7.2
install:
  - phpize
  - ./configure
  - make
  - make install
script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_ARGS="--show-diff"
  - make test
